import { makeStyles, tokens } from "@fluentui/react-components";

export const useAdminPanelStyles = makeStyles({
    body: {
        display: "flex",
        flexDirection: "column",
        gap: "16px",
        paddingTop: "8px",
        paddingBottom: "8px",
        overflow: "hidden",
    },
    tabContent: {
        display: "flex",
        flexDirection: "column",
        gap: "8px",
        overflowY: "auto",
        flex: 1,
    },
    center: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        padding: "48px 0",
    },
    emptyState: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "8px",
        padding: "48px 0",
        color: tokens.colorNeutralForeground3,
    },
    // user item
    userItem: {
        display: "flex",
        alignItems: "center",
        gap: "12px",
        padding: "10px 12px",
        borderRadius: tokens.borderRadiusMedium,
        background: tokens.colorNeutralBackground2,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
    },
    userInfo: {
        display: "flex",
        flexDirection: "column",
        gap: "2px",
        overflow: "hidden",
    },
    userName: {
        fontSize: tokens.fontSizeBase300,
        fontWeight: tokens.fontWeightSemibold,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    userId: {
        fontSize: tokens.fontSizeBase100,
        color: tokens.colorNeutralForeground3,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    dataGridWrapper: {
        overflowX: "auto",
    },
    dataGrid: {
        minWidth: "1000px",
    },
    userGridRow: {
        padding: '10px 0',
    },
    // feedback item (legacy list view — kept for drawer reuse)
    feedbackAnswerLabel: {
        fontSize: tokens.fontSizeBase100,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorBrandForeground1,
        textTransform: "uppercase",
        letterSpacing: "0.04em",
    },
    feedbackPanelBody: {
        display: "flex",
        flexDirection: "column",
        gap: "12px",
        paddingBottom: "24px",
    },
    feedbackDialogMessage: {
        padding: "10px 12px",
        borderRadius: tokens.borderRadiusMedium,
        background: tokens.colorNeutralBackground3,
        fontSize: tokens.fontSizeBase300,
        color: tokens.colorNeutralForeground2,
        whiteSpace: "pre-wrap",
    },
    // kanban board
    kanbanBoard: {
        display: "grid",
        gridTemplateColumns: "repeat(3, minmax(180px, 1fr))",
        gap: "12px",
        alignItems: "start",
    },
    kanbanColumn: {
        display: "flex",
        flexDirection: "column",
        borderRadius: tokens.borderRadiusMedium,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        background: tokens.colorNeutralBackground2,
        overflow: "hidden",
        transition: "border-color 0.15s, background 0.15s",
    },
    kanbanColumnDragOver: {
        background: tokens.colorNeutralBackground3,
        borderColor: tokens.colorBrandForeground1,
    },
    kanbanColumnHeader: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        padding: "10px 12px",
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    },
    kanbanDot: {
        width: "8px",
        height: "8px",
        borderRadius: tokens.borderRadiusCircular,
        flexShrink: 0,
    },
    kanbanColumnTitle: {
        flex: 1,
        fontSize: tokens.fontSizeBase100,
        fontWeight: tokens.fontWeightSemibold,
        textTransform: "uppercase",
        letterSpacing: "0.06em",
        color: tokens.colorNeutralForeground3,
    },
    kanbanColumnCount: {
        fontSize: tokens.fontSizeBase100,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground3,
        background: tokens.colorNeutralBackground1,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRadius: tokens.borderRadiusCircular,
        padding: "1px 7px",
        minWidth: "20px",
        textAlign: "center",
    },
    kanbanCards: {
        display: "flex",
        flexDirection: "column",
        gap: "6px",
        padding: "8px",
        minHeight: "80px",
    },
    kanbanCard: {
        display: "flex",
        flexDirection: "column",
        gap: "8px",
        padding: "12px",
        borderRadius: tokens.borderRadiusMedium,
        background: tokens.colorNeutralBackground1,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        cursor: "grab",
        userSelect: "none",
        ":hover": {
            background: tokens.colorNeutralBackground1Hover,
            borderColor: tokens.colorNeutralStroke1Hover,
        },
        ":active": {
            background: tokens.colorNeutralBackground1Pressed,
        },
    },
    kanbanCardMessage: {
        fontSize: tokens.fontSizeBase300,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground1,
        display: "-webkit-box",
        WebkitLineClamp: "2",
        WebkitBoxOrient: "vertical",
        overflow: "hidden",
        lineHeight: "1.4",
    },
    kanbanCardFooter: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: "6px",
    },
    kanbanCardSource: {
        display: "flex",
        alignItems: "center",
        gap: "4px",
        fontSize: tokens.fontSizeBase100,
        color: tokens.colorNeutralForeground3,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    kanbanCardSourceIcon: {
        fontSize: "12px",
        flexShrink: 0,
    },
    kanbanCardDate: {
        flexShrink: 0,
        fontSize: tokens.fontSizeBase100,
        color: tokens.colorNeutralForeground3,
        whiteSpace: "nowrap",
    },
    kanbanTag: {
        alignSelf: "flex-start",
        fontSize: tokens.fontSizeBase100,
        fontWeight: tokens.fontWeightSemibold,
        borderRadius: tokens.borderRadiusMedium,
        padding: "2px 8px",
    },
    kanbanTagFeature: {
        color: tokens.colorPaletteTealForeground2,
        background: tokens.colorPaletteTealBackground2,
    },
    kanbanTagBug: {
        color: tokens.colorPaletteRedForeground1,
        background: tokens.colorPaletteRedBackground2,
    },
    kanbanTagPerformance: {
        color: tokens.colorPaletteMarigoldForeground2,
        background: tokens.colorPaletteMarigoldBackground2,
    },
    kanbanTagUX: {
        color: tokens.colorPalettePurpleForeground2,
        background: tokens.colorPalettePurpleBackground2,
    },
    feedbackTabToolbar: {
        display: "flex",
        justifyContent: "flex-end",
        paddingBottom: "4px",
    },
});
