import { makeStyles, tokens } from "@fluentui/react-components";

export const useKanbanColumnStyles = makeStyles({
    kanbanColumn: {
        display: "flex",
        flexDirection: "column",
        borderRadius: tokens.borderRadiusMedium,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        background: tokens.colorNeutralBackground2,
        overflow: "hidden",
        transition: "border-color 0.15s, background 0.15s",
    },
    kanbanColumnExpanded: {
        flex: 1,
        minWidth: "180px",
    },
    kanbanColumnCollapsed: {
        width: "44px",
        flexShrink: 0,
        alignItems: "center",
        height: "210px",
        paddingTop: "12px",
    },
    kanbanCollapsedBody: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "flex-end",
        gap: "8px",
        padding: "8px 0",
        flex: 1,
    },
    kanbanColumnTitleVertical: {
        fontSize: tokens.fontSizeBase200,
        fontWeight: tokens.fontWeightBold,
        textTransform: "uppercase",
        letterSpacing: "0.06em",
        color: tokens.colorNeutralForeground2,
        writingMode: "vertical-rl",
        transform: "rotate(180deg)",
    },
    kanbanColumnDragOver: {
        background: tokens.colorNeutralBackground3,
        border: `1px solid ${tokens.colorBrandForeground1}`,
    },
    kanbanColumnHeader: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        padding: "10px 12px",
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    },
    kanbanDot: {
        width: "8px",
        height: "8px",
        borderRadius: tokens.borderRadiusCircular,
        flexShrink: 0,
    },
    kanbanColumnTitle: {
        flex: 1,
        fontSize: tokens.fontSizeBase100,
        fontWeight: tokens.fontWeightSemibold,
        textTransform: "uppercase",
        letterSpacing: "0.06em",
        color: tokens.colorNeutralForeground3,
    },
    kanbanColumnCount: {
        fontSize: tokens.fontSizeBase100,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground3,
        background: tokens.colorNeutralBackground1,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRadius: tokens.borderRadiusCircular,
        padding: "1px 7px",
        minWidth: "20px",
        textAlign: "center",
    },
    kanbanCards: {
        display: "flex",
        flexDirection: "column",
        gap: "6px",
        padding: "8px",
        minHeight: "80px",
    },
});
