import { makeStyles, tokens } from "@fluentui/react-components";
import { breakpoints } from "../common/styles/breakpoints";

const desktopOnly = "@media (min-width: 769px)";

export const useDayCardListStyles = makeStyles({
    monthNav: {
        position: "sticky",
        top: "calc(56px + env(safe-area-inset-top) + 8px)",
        zIndex: 10,
        display: "flex",
        justifyContent: "center",
        pointerEvents: "none",
        marginBottom: "16px",
        paddingTop: "32px",
        [desktopOnly]: {
            paddingTop: "0px",
        },
    },
    monthNavPillWrapper: {
        position: "relative",
        display: "inline-flex",
    },
    monthNavAction: {
        borderRadius: tokens.borderRadiusCircular,
    },
    monthNavPill: {
        display: "flex",
        alignItems: "center",
        gap: "4px",
        padding: "4px",
        background: tokens.colorNeutralBackground1,
        borderRadius: tokens.borderRadiusCircular,
        boxShadow: tokens.shadow16,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        pointerEvents: "all",
    },
    todayNub: {
        position: "absolute",
        bottom: "calc(100% - 1px)",
        left: "50%",
        transform: "translateX(-50%) scaleY(0)",
        transformOrigin: "bottom",
        opacity: 0,
        pointerEvents: "none",
        [desktopOnly]: {
            display: "none",
        },
        background: tokens.colorNeutralBackground1,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        borderBottom: "none",
        borderRadius: "10px 10px 0 0",
        padding: "6px 14px 8px",
        display: "flex",
        alignItems: "center",
        gap: "6px",
        cursor: "pointer",
        whiteSpace: "nowrap",
        transitionProperty: "transform, opacity",
        transitionDuration: "0.35s, 0.2s",
        transitionTimingFunction: "cubic-bezier(0.34, 1.4, 0.64, 1), ease",
        userSelect: "none",
    },
    todayNubVisible: {
        transform: "translateX(-50%) scaleY(1)",
        opacity: 1,
        pointerEvents: "all",
    },
    todayNubDot: {
        width: "7px",
        height: "7px",
        borderRadius: tokens.borderRadiusCircular,
        backgroundColor: tokens.colorBrandForeground1,
        flexShrink: 0,
        display: "inline-block",
    },
    todayNubText: {
        fontSize: "11px",
        color: tokens.colorNeutralForeground3,
        fontWeight: "500",
        letterSpacing: "0.02em",
        lineHeight: 1,
    },
    fab: {
        position: "fixed",
        bottom: "32px",
        right: "32px",
        boxShadow: tokens.shadow16,
    },
    grid: {
        display: "grid",
        gridTemplateColumns: "repeat(7, 1fr)",
        gap: "8px",
        [breakpoints.mobile]: {
            display: "flex",
            flexWrap: "nowrap",
            overflowX: "auto",
            scrollSnapType: "x mandatory",
            justifyContent: "flex-start",
            padding: "4px 20px 16px",
            scrollbarWidth: "none",
            msOverflowStyle: "none",
            "::-webkit-scrollbar": { display: "none" },
        },
    },
    weekDayHeader: {
        textAlign: "center",
        fontSize: "11px",
        fontWeight: "600",
        color: tokens.colorNeutralForeground3,
        textTransform: "uppercase",
        letterSpacing: "0.05em",
        padding: "4px 0 8px",
        [breakpoints.mobile]: {
            display: "none",
        },
    },
    desktopLayout: {
        display: "block",
        [breakpoints.mobile]: {
            display: "none",
        },
    },
    desktopColumns: {
        display: "flex",
        gap: "24px",
        alignItems: "center",
    },
    calendarSide: {
        flex: "0 0 65%",
        width: "65%",
    },
    detailSide: {
        flex: 1,
        position: "sticky",
        top: "calc(56px + env(safe-area-inset-top) + 16px)",
    },
    mobileLayout: {
        display: "none",
        [breakpoints.mobile]: {
            display: "block",
        },
    },
    mobileGrid: {
        display: "flex",
        flexWrap: "nowrap",
        overflowX: "auto",
        scrollSnapType: "x mandatory",
        justifyContent: "flex-start",
        padding: "4px 20px 16px",
        scrollbarWidth: "none",
        msOverflowStyle: "none",
        gap: "12px",
        "::-webkit-scrollbar": { display: "none" },
    },
});
